---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-backup
  namespace: test
  labels:
    app: kafka-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-backup
  template:
    metadata:
      labels:
        app: kafka-backup
    spec:
      containers:
      - name: kafka-backup
        image: khinkali/kafka-backup:todo
        env:
        - name: KAFKA_ADDRESS
          value: "kafka:9092"
        - name: VERSION
          value: "todo"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /kafka-backup/resources/health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-backup
  namespace: test
spec:
  selector:
    app: kafka-backup
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31082
  type: NodePort
